import { Task } from './shared/models/task-model';

export const sample_tasks: Task[] = [
  {
    id: 0,
    name: 'Kup mleko',
    description: 'Kupić mleko w pobliskim sklepie',
    dueDate: new Date('2025-12-05T10:00:00'),
    isCompleted: false,
    isDeleted: false,
  },
  {
    id: 1,
    name: 'Zrobić pranie',
    description: 'Wrzucić ubrania do pralki i zrobić pranie',
    dueDate: new Date('2025-12-04T18:00:00'),
    isCompleted: false,
    isDeleted: false,
  },
  {
    id: 2,
    name: 'Spotkanie z zespołem',
    description: 'Omówić nowe funkcje projektu',
    dueDate: new Date('2025-12-06T14:00:00'),
    isCompleted: false,
    isDeleted: false,
  },
  {
    id: 3,
    name: 'Przeczytać książkę',
    description: "Przeczytać rozdział 5 książki 'TypeScript Basics'",
    dueDate: new Date('2025-12-10T20:00:00'),
    isCompleted: false,
    isDeleted: false,
  },
  {
    id: 4,
    name: 'Wyjście na spacer',
    description: 'Wyjść na 30-minutowy spacer po obiedzie',
    dueDate: new Date('2025-12-03T17:00:00'),
    isCompleted: false,
    isDeleted: false,
  },
  {
    id: 5,
    name: 'Usunięte zadanie',
    description: 'To zadanie zostało usunięte',
    dueDate: new Date('2025-12-02T12:00:00'),
    isCompleted: false,
    isDeleted: true,
  },
  {
    id: 6,
    name: 'Zadanie ukończone',
    description: 'To zadanie zostało ukończone',
    dueDate: new Date('2025-12-01T09:00:00'),
    isCompleted: true,
    isDeleted: false,
  },
];
