export const sample_lists: any[] = [
  {
    id: 0,
    name: "Lista Testowa 2",
    isPinned: true,
  },
  {
    id: 1,
    name: "Lista Testowa",
    isPinned: true,
  },
];

export const sample_tags: any[] = [
  { id: 0, emoji: "🛒", name: "Zakupy" },
  { id: 1, emoji: "📚", name: "Nauka" },
  { id: 2, emoji: "💼", name: "Praca" },
  { id: 3, emoji: "🏃", name: "Zdrowie" },
];

export const sample_tasks: any[] = [
  {
    id: 0,
    name: "Kup mleko",
    description: "Kupić mleko w pobliskim sklepie",
    dueDate: new Date("2025-12-02T10:00:00"),
    isCompleted: false,
    isDeleted: false,
    tags: [sample_tags[0], sample_tags[3]],
    list: sample_lists[1],
  },
  {
    id: 1,
    name: "Zrobić pranie",
    description: "Wrzucić ubrania do pralki i zrobić pranie",
    dueDate: new Date("2025-12-04T18:00:00"),
    isCompleted: false,
    isDeleted: false,
    tags: [sample_tags[3]],
    list: sample_lists[0],
  },
  {
    id: 2,
    name: "Spotkanie z zespołem",
    description: "Omówić nowe funkcje projektu",
    dueDate: new Date("2025-12-06T14:00:00"),
    isCompleted: false,
    isDeleted: false,
    tags: [sample_tags[2], sample_tags[1]],
  },
  {
    id: 3,
    name: "Przeczytać książkę",
    description: "Przeczytać rozdział 5 książki 'TypeScript Basics'",
    dueDate: new Date("2025-12-10T20:00:00"),
    isCompleted: false,
    isDeleted: false,
    tags: [sample_tags[1], sample_tags[3]],
  },
  {
    id: 4,
    name: "Wyjście na spacer",
    description: "Wyjść na 30-minutowy spacer po obiedzie",
    dueDate: new Date("2025-12-03T17:00:00"),
    isCompleted: false,
    isDeleted: false,
    tags: [sample_tags[3], sample_tags[0]],
    list: sample_lists[0],
  },
  {
    id: 5,
    name: "Usunięte zadanie",
    description: "To zadanie zostało usunięte",
    dueDate: new Date("2025-12-02T12:00:00"),
    isCompleted: false,
    isDeleted: true,
    tags: [sample_tags[2]],
  },
  {
    id: 6,
    name: "Zadanie ukończone",
    description: "To zadanie zostało ukończone",
    dueDate: new Date("2025-12-01T09:00:00"),
    isCompleted: true,
    isDeleted: false,
    tags: [sample_tags[1], sample_tags[0]],
  },
  {
    id: 7,
    name: "Week test",
    description: "Wyjść na 30-minutowy spacer po obiedzie",
    dueDate: new Date("2025-12-07T17:00:00"),
    isCompleted: false,
    isDeleted: false,
    tags: [sample_tags[3], sample_tags[2], sample_tags[1]],
  },
];
